ProjectTracker/Models/Employee.cs
namespace ProjectTracker.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
    }
}

ProjectTracker/ViewModels/ProjectViewModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using ProjectTracker.Domain.Entities.Base.Interface;
using ProjectTracker.Domain.Entities.Base.Tags;

namespace ProjectTracker.ViewModels
{
    public class ProjectViewModel: INamedEntity, IDescriptionEntity
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Display(Name = "Название")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Обязательное поле")]
        public string? Name { get; set; }

        [Display(Name = "Опесание")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Обязательное поле")]
        public string? Description { get; set; }

        public DateTime StartDate { get; set; } = DateTime.Now;

        public ProjectStatus Status { get; set; } = ProjectStatus.Active;

        //public List<TaskViewModel> Tasks { get; set; } = new List<TaskViewModel>();
    }
}

ProjectTracker/ViewModels/TaskViewModel.cs
using ProjectTracker.Domain.Entities.Base.Interface;
using ProjectTracker.Domain.Entities.Base.Tags;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using TaskStatus = ProjectTracker.Domain.Entities.Base.Tags.TaskStatus;

namespace ProjectTracker.ViewModels
{
    public class TaskViewModel : INamedEntity, IDescriptionEntity
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Display(Name = "Название")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Обязательное поле")]
        public string? Name { get; set; }

        [Display(Name = "Опесание")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Обязательное поле")]
        public string? Description { get; set; }

        public TaskPriority Priority { get; set; }
        public TaskStatus Status { get; set; }
        public DateTime Deadline { get; set; }

        public int? ProjectId { get; set; }
    }
}

ProjectTracker/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectTracker.Infrastructure.Interfaces;
using ProjectTracker.Infrastructure.Mapping;
using ProjectTracker.ViewModels;

namespace ProjectTracker.Controllers
{
    public class EmployeeController : Controller
    {
        //private readonly IProjectData _projectData;
        //private readonly IDataService _dataService;

        //public EmployeeController(IProjectData projectData, IDataService dataService)
        //{
        //    _projectData = projectData;
        //    _dataService = dataService;
        //}

        //public IActionResult Index()
        //{
        //    _dataService.Add(new ProjectViewModel());
        //}

    }
}

ProjectTracker/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectTracker.Infrastructure.Interfaces;
using ProjectTracker.Infrastructure.Mapping;
using ProjectTracker.Infrastructure.Services;
using ProjectTracker.ViewModels;
using TaskStatus = ProjectTracker.Domain.Entities.Base.Tags.TaskStatus;

namespace ProjectTracker.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectData _projectData;
        private readonly ProjectService _projectService;

        public ProjectController(IProjectData projectData, ProjectService projectService)
        {
            _projectData = projectData;
            _projectService = projectService;
        } 

        public IActionResult Index()
        {
            var projects = _projectData.GetProjects().Select(project => project.ToView()).ToList();

            return View(projects);
        }

        public IActionResult Details(int id)
        {
            var project = _projectData.GetTasksById(id);
            if (project is null)
            {
                return NotFound();
            } 

            return View(project.ToView());
        }

        public IActionResult Create(int id)
        {

            var project = new ProjectViewModel();

            ViewBag.Status = Enum.GetValues(typeof(TaskStatus))
                .Cast<TaskStatus>()
                .Select(e => new SelectListItem()
                {
                    Text = e.ToString(),
                });
            return View(new ProjectViewModel());
        }

        [HttpPost]
        public IActionResult Create(ProjectViewModel viewModel)
        {
            if (viewModel is null)
                throw new ArgumentException(nameof(viewModel));

            if (!ModelState.IsValid)
                return View(viewModel);

            _projectService.Add(viewModel.FromView());

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if (id is null)
                return View(new ProjectViewModel());

            if (id < 0)
                return BadRequest();

            var item = _projectService.GetById(id);

            return View(item.ToView());
        }

        [HttpPost]
        public IActionResult Edit(int id, ProjectViewModel viewModel)
        {
            if (viewModel is null)
            {
                throw new ArgumentNullException(nameof(viewModel));
            }

            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            _projectService.Edit(id, viewModel.FromView());
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id <= 0)
                return BadRequest();

            var item = _projectService.GetById(id);

            if (item is null)
                return NotFound();

            return View(item.ToView());
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            _projectService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

ProjectTracker/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectTracker.Infrastructure.Interfaces;
using ProjectTracker.Infrastructure.Mapping;
using ProjectTracker.Infrastructure.Services;
using ProjectTracker.ViewModels;

namespace ProjectTracker.Controllers
{
    public class TaskController : Controller
    {

        private readonly IProjectData _projectData;
        private readonly TaskService _taskService;

        public TaskController(IProjectData projectData, TaskService taskService)
        {
            _projectData = projectData;
            _taskService = taskService;
        }

        public IActionResult Index()
        {
            var task = _projectData.GetTasks();

            return View(task.ToView());
        }

        public IActionResult Create(int id)
        {
            return View(new TaskViewModel());
        }

        [HttpPost]
        public IActionResult Create(TaskViewModel viewModel)
        {
            if (viewModel is null)
                throw new ArgumentNullException(nameof(viewModel));

            if (!ModelState.IsValid)
                return View(viewModel);

            _taskService.Add(viewModel.FromView());


            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if (id is null)
                return View(new TaskViewModel());

            if (id < 0)
                return BadRequest();

            var item = _taskService.GetById(id);
            return View(item.ToView());
        }

        [HttpPost]
        public IActionResult Edit(int id, TaskViewModel viewModel)
        {
            if (viewModel is null)
            {
                throw new ArgumentNullException(nameof(viewModel));
            }

            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            _taskService.Edit(id, viewModel.FromView());
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id <= 0)
                return BadRequest();

            var item = _taskService.GetById(id);

            if (item is null)
                return NotFound();

            return View(item.ToView());
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            _taskService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

ProjectTracker/Views/Project/Create.cshtml
@model ProjectViewModel

<body>
    <div class="container py-4">
        <!--  <div class="row mb-4">
            <div class="row mb-4">
                <h1 class="text-center">Создать новый проект</h1>
            </div>
        </div>

        <div class="mb-3">
            <label asp-for="Name" class="form-label">Название</label>
            <input type="text" class="form-controll" id="name" placeholder="Введите название"/>
       
        </div>
        <div class="mb-3">
            <label asp-for="Description" class="form-label">Описание</label>
            <textarea class="form-controll" id="description" rows="3" placeholder="Описание"></textarea>
            
        </div>
        
        <div class="mb-3">
            <label asp-for="Status"  class="form-label">Статус</label>
            <select class="form-select" id="status" name="status">
                <option selected value="">Выберите статус</option>
                @*    @foreach (var status in ViewBag.Status)
                {
                    <option value="@status">@status</option>
                } *@
            </select>
        </div>
        
        <div class="d-flex gap-2 mt-4">
            <button type="submit" class="btn btn-primary px-4">Создать</button>
        </div>-->

        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden"/>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

        @*     <div class="mb-3">
                <label asp-for="Status"  class="form-label">Статус</label>
                <select asp-for="Status" asp-items="ViewBag.Status" class="form-select">
                    <option selected value="">Выберите статус</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div> *@

            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-default"/>
            </div>
        </form>

    </div>
</body>

ProjectTracker/Views/Project/Delete.cshtml
@model ProjectViewModel

@{
    ViewData["Title"] = "Delete";
}

<div class="container">
    <h2>Delete</h2>
    
    <div Project></div>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete" asp-route-id="@Model.Id">
        <input type="submit" value="Удалить" class="btn btn-default"/>
        <a asp-action="Index">Назад</a>
    </form>
</div>

ProjectTracker/Views/Project/Details.cshtml
@model IEnumerable<TaskViewModel>

@{
    ViewBag.Title = "Проект #" + Model.FirstOrDefault(model => model.ProjectId != 0)!.ProjectId;
}

<div class="container mt-4">
    <h3>@ViewData["Title"]</h3>
    <hr />
    <table class="table table striped table-hover">
        <thead class="table-dark">
            <tr>
                <th>#</th>
                <th>Название</th>
                <th>Описание</th>
                <th>Приоритет</th>
                <th>Статус</th>
                <th>Срок сдачи</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Description</td>
                    <td>@item.Priority</td>
                    <td>@item.Status</td>
                    <td>@item.Deadline</td>
                </tr>
            }

        </tbody>
    </table>


</div>

ProjectTracker/Views/Project/Edit.cshtml
@model ProjectViewModel

@{
    ViewBag.Title = "Редактирование проекта Id:" + Model.Id;
}

<div class="container">
    <h3>@ViewData["Title"]</h3>
    <hr/>
    
    <form asp-action="Edit" method="post">
        <div class="row">
            <div class="col-md-4">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                
                <input asp-for="Id" type="hidden"/>
                
                <div class="form-group">
                    <label asp-for="Name" class="control-lable"></label>
                    <input asp-for="Name" class="form-control"/>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                
                <div class="form-group">
                    <label asp-for="Description" class="control-lable"></label>
                    <input asp-for="Description" class="form-control"/>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                
                <div class="form-group">
                    <input type="submit" value="Сохранить" class="btn btn-default"/>
                </div>
        
            </div>
        </div>
    </form>
</div>

ProjectTracker/Views/Project/Index.cshtml
@model IEnumerable<ProjectViewModel>

@{
    ViewBag.Title = "Проекты";
}

<div class="container mt-4">
    <table class="table table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th>#</th>
                <th>Название</th>
                <th>Описание</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var project in Model)
            {
                <tr>
                    <td>@project.Id</td>
                    <td>@project.Name</td>
                    <td>@project.Description</td>
                    <td>
                        <a asp-controller="Project" asp-action="Details" asp-route-id="@project.Id">Открыть</a>
                    </td>

                    <td>
                        <a asp-controller="Project" asp-action="Edit" asp-route-id="@project.Id">Редактировать</a>
                    </td>

                    <td>
                        <a asp-controller="Project" asp-action="Delete" asp-route-id="@project.Id">Удалить</a>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>

ProjectTracker/Views/Shared/Partial/_Header.cshtml
<!-- Шапка сайта -->
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
            <!--логотип -->
            <a class="navbar-brand" >Список проектов</a>
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Project" asp-action="Index">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Project" asp-action="Index">Проекты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Task" asp-action="Index">Задачи</a>
                    </li>
                </ul>
            </div>
    </div>
</nav>
</body>

ProjectTracker/Views/Shared/Partial/_Styles.cshtml
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"/>

ProjectTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    
    @await Html.PartialAsync("Partial/_Styles")
    @await RenderSectionAsync("Styles", false)
</head>
<body>
<div>    
    
    @await Html.PartialAsync("Partial/_Header")

    @RenderBody()
    </div>
</body>
</html>

ProjectTracker/Views/Task/Create.cshtml
@model TaskViewModel

<body>
    <div class="container py-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden" />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </form>
    </div>
</body>

ProjectTracker/Views/Task/Delete.cshtml
@model TaskViewModel

@{
    ViewData["Title"] = "Delete";
}

<div class="container">
    <h2>Delete</h2>

    <div Task></div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>

    <form asp-action="Delete" asp-route-id="@Model.Id">
        <input type="submit" value="Удалить" class="btn btn-default" />
        <a asp-action="Index">Назад</a>
    </form>
</div>

ProjectTracker/Views/Task/Edit.cshtml
@model TaskViewModel

@{
    ViewBag.Title = "Редактирование проекта Id:" + Model.Id;
}

<div class="container">
    <h3>@ViewData["Title"]</h3>
    <hr />

    <form asp-action="Edit" method="post">
        <div class="row">
            <div class="col-md-4">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <input asp-for="Id" type="hidden" />

                <div class="form-group">
                    <label asp-for="Name" class="control-lable"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description" class="control-lable"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Сохранить" class="btn btn-default" />
                </div>

            </div>
        </div>
    </form>
</div>

ProjectTracker/Views/Task/Index.cshtml
@model IEnumerable<TaskViewModel>

@{
    ViewBag.Title = "Проекты";
}

<div class="container mt-4">
    <table class="table table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th>#</th>
                <th>Название</th>
                <th>Описание</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var project in Model)
            {
                <tr>
                    <td>@project.Id</td>
                    <td>@project.Name</td>
                    <td>@project.Description</td>
                    <td>
                        <td>
                            <a asp-controller="Task" asp-action="Edit" asp-route-id="@project.Id">Редактировать</a>
                        </td>

                        <td>
                            <a asp-controller="Task" asp-action="Delete" asp-route-id="@project.Id">Удалить</a>
                        </td>
                </td>
                </tr>
            }
        </tbody>

    </table>
</div>